[2021-02-01 06:38:07,410] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: comic_app_v2.send_notification 2021-02-01T06:37:56.668207+00:00 [queued]>
[2021-02-01 06:38:07,427] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: comic_app_v2.send_notification 2021-02-01T06:37:56.668207+00:00 [queued]>
[2021-02-01 06:38:07,427] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-02-01 06:38:07,427] {taskinstance.py:881} INFO - Starting attempt 1 of 3
[2021-02-01 06:38:07,427] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-02-01 06:38:07,436] {taskinstance.py:901} INFO - Executing <Task(SlackAPIPostOperator): send_notification> on 2021-02-01T06:37:56.668207+00:00
[2021-02-01 06:38:07,439] {standard_task_runner.py:54} INFO - Started process 426 to run task
[2021-02-01 06:38:07,469] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'comic_app_v2', 'send_notification', '2021-02-01T06:37:56.668207+00:00', '--job_id', '25', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/manga.py', '--cfg_path', '/tmp/tmp7zqnmzh9']
[2021-02-01 06:38:07,470] {standard_task_runner.py:78} INFO - Job 25: Subtask send_notification
[2021-02-01 06:38:07,493] {logging_mixin.py:112} INFO - Running <TaskInstance: comic_app_v2.send_notification 2021-02-01T06:37:56.668207+00:00 [running]> on host 5e1208a57967
[2021-02-01 06:38:08,017] {taskinstance.py:1150} ERROR - Slack API call failed (invalid_auth)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/slack_operator.py", line 85, in execute
    slack.call(self.method, self.api_params)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/slack_hook.py", line 62, in call
    raise AirflowException(msg)
airflow.exceptions.AirflowException: Slack API call failed (invalid_auth)
[2021-02-01 06:38:08,018] {taskinstance.py:1194} INFO - Marking task as UP_FOR_RETRY. dag_id=comic_app_v2, task_id=send_notification, execution_date=20210201T063756, start_date=20210201T063807, end_date=20210201T063808
[2021-02-01 06:38:12,397] {local_task_job.py:102} INFO - Task exited with return code 1
