[2021-02-02 05:07:54,010] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: test_slack_0.0.1.send_slack 2021-02-02T05:07:50.238066+00:00 [queued]>
[2021-02-02 05:07:54,026] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: test_slack_0.0.1.send_slack 2021-02-02T05:07:50.238066+00:00 [queued]>
[2021-02-02 05:07:54,026] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-02-02 05:07:54,026] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2021-02-02 05:07:54,026] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-02-02 05:07:54,032] {taskinstance.py:901} INFO - Executing <Task(SlackAPIPostOperator): send_slack> on 2021-02-02T05:07:50.238066+00:00
[2021-02-02 05:07:54,035] {standard_task_runner.py:54} INFO - Started process 1237 to run task
[2021-02-02 05:07:54,065] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'test_slack_0.0.1', 'send_slack', '2021-02-02T05:07:50.238066+00:00', '--job_id', '39', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/slack_message.py', '--cfg_path', '/tmp/tmpw84jw444']
[2021-02-02 05:07:54,066] {standard_task_runner.py:78} INFO - Job 39: Subtask send_slack
[2021-02-02 05:07:54,091] {logging_mixin.py:112} INFO - Running <TaskInstance: test_slack_0.0.1.send_slack 2021-02-02T05:07:50.238066+00:00 [running]> on host 5e1208a57967
[2021-02-02 05:07:54,618] {taskinstance.py:1150} ERROR - Slack API call failed (not_in_channel)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/slack_operator.py", line 85, in execute
    slack.call(self.method, self.api_params)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/slack_hook.py", line 62, in call
    raise AirflowException(msg)
airflow.exceptions.AirflowException: Slack API call failed (not_in_channel)
[2021-02-02 05:07:54,619] {taskinstance.py:1194} INFO - Marking task as FAILED. dag_id=test_slack_0.0.1, task_id=send_slack, execution_date=20210202T050750, start_date=20210202T050754, end_date=20210202T050754
[2021-02-02 05:07:59,006] {local_task_job.py:102} INFO - Task exited with return code 1
